services:
  web:
    build: ./
    volumes:
      - .:/rails 
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password123@db:5432/quicket_development

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: quicket_development
    ports:
      - "5432:5432"

volumes:
  db_data: {}
